ALTER TABLE IF EXISTS "user" RENAME TO users;
ALTER TABLE IF EXISTS credit_card RENAME TO credit_cards;
ALTER TABLE IF EXISTS region RENAME TO regions;
ALTER TABLE IF EXISTS category RENAME TO categories;
ALTER TABLE IF EXISTS winery RENAME TO wineries;
ALTER TABLE IF EXISTS "order" RENAME TO orders;
ALTER TABLE IF EXISTS wine RENAME TO wines;
ALTER TABLE IF EXISTS "user" RENAME TO users;
ALTER TABLE IF EXISTS product RENAME TO products;




